name: Tests

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.1'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: nette/code-checker:3.3

      - name: Install dependencies
        run: composer install

      - name: Run Nette code-checker
        run: code-checker --short-arrays -d app

      - name: Run PHP-CS-Fixer
        run: composer run-script cs

      - name: Run tests
        run: |
          mv app/config/config.local.neon.default app/config/config.local.neon
          composer test
